"""Adding account activation

Revision ID: 67a8bf5e9eec
Revises: 30a153e8f3a5
Create Date: 2020-08-12 18:59:53.593594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a8bf5e9eec'
down_revision = '30a153e8f3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('activation_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('activation_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_sent_at')
    op.drop_column('users', 'activation_hash')
    op.drop_column('users', 'activated')
    # ### end Alembic commands ###
