"""Adding password reset

Revision ID: 9bbd025744ac
Revises: 67a8bf5e9eec
Create Date: 2020-08-12 21:31:12.683211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbd025744ac'
down_revision = '67a8bf5e9eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_sent_at')
    op.drop_column('users', 'reset_hash')
    # ### end Alembic commands ###
